// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `rdbdata.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.icestorm.RdbRealData;

public interface RdbDataOpt extends Ice.Object,
                                    _RdbDataOptOperations, _RdbDataOptOperationsNC
{
    public static final String ice_staticId = "::RdbRealData::RdbDataOpt";

    public static final long serialVersionUID = 368022828L;
}
