// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `eventdata.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <eventdata.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __EventData__EventDataManager__send_name = "send";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::EventData::upCast(::IceProxy::EventData::EventDataManager* p) { return p; }

void
::IceProxy::EventData::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::EventData::EventDataManager>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::EventData::EventDataManager;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::EventData::EventDataManager::send(const ::EventData::eventContentSeq& __p_eventMsgSeq, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __EventData__EventDataManager__send_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_eventMsgSeq);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::EventData::EventDataManager::begin_send(const ::EventData::eventContentSeq& __p_eventMsgSeq, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EventData__EventDataManager__send_name, __del, __cookie);
    try
    {
        __result->prepare(__EventData__EventDataManager__send_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_eventMsgSeq);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::EventData::EventDataManager::end_send(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __EventData__EventDataManager__send_name);
}

const ::std::string&
IceProxy::EventData::EventDataManager::ice_staticId()
{
    return ::EventData::EventDataManager::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::EventData::EventDataManager::__newInstance() const
{
    return new EventDataManager;
}

::Ice::Object* EventData::upCast(::EventData::EventDataManager* p) { return p; }

namespace
{
const ::std::string __EventData__EventDataManager_ids[2] =
{
    "::EventData::EventDataManager",
    "::Ice::Object"
};

}

bool
EventData::EventDataManager::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__EventData__EventDataManager_ids, __EventData__EventDataManager_ids + 2, _s);
}

::std::vector< ::std::string>
EventData::EventDataManager::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__EventData__EventDataManager_ids[0], &__EventData__EventDataManager_ids[2]);
}

const ::std::string&
EventData::EventDataManager::ice_id(const ::Ice::Current&) const
{
    return __EventData__EventDataManager_ids[0];
}

const ::std::string&
EventData::EventDataManager::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::EventData::EventDataManager";
    return typeId;
#else
    return __EventData__EventDataManager_ids[0];
#endif
}

::Ice::DispatchStatus
EventData::EventDataManager::___send(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EventData::eventContentSeq __p_eventMsgSeq;
    __is->read(__p_eventMsgSeq);
    __inS.endReadParams();
    send(__p_eventMsgSeq, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __EventData__EventDataManager_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "send"
};

}

::Ice::DispatchStatus
EventData::EventDataManager::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__EventData__EventDataManager_all, __EventData__EventDataManager_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __EventData__EventDataManager_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___send(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
EventData::EventDataManager::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
EventData::EventDataManager::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
EventData::__patch(EventDataManagerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::EventData::EventDataManagerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::EventData::EventDataManager::ice_staticId(), v);
    }
}
