// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `fepcmd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <fepcmd.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __FepCmd__CCallAllFep__CallAllExecute_name = "CallAllExecute";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::FepCmd::upCast(::IceProxy::FepCmd::CCallAllFep* p) { return p; }

void
::IceProxy::FepCmd::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::FepCmd::CCallAllFep>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::FepCmd::CCallAllFep;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::FepCmd::CCallAllFep::CallAllExecute(const ::FepCmd::CallAllInfo& __p_caInfo, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __FepCmd__CCallAllFep__CallAllExecute_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_caInfo);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::FepCmd::CCallAllFep::begin_CallAllExecute(const ::FepCmd::CallAllInfo& __p_caInfo, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FepCmd__CCallAllFep__CallAllExecute_name, __del, __cookie);
    try
    {
        __result->prepare(__FepCmd__CCallAllFep__CallAllExecute_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_caInfo);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::FepCmd::CCallAllFep::end_CallAllExecute(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FepCmd__CCallAllFep__CallAllExecute_name);
}

const ::std::string&
IceProxy::FepCmd::CCallAllFep::ice_staticId()
{
    return ::FepCmd::CCallAllFep::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::FepCmd::CCallAllFep::__newInstance() const
{
    return new CCallAllFep;
}

::Ice::Object* FepCmd::upCast(::FepCmd::CCallAllFep* p) { return p; }

namespace
{
const ::std::string __FepCmd__CCallAllFep_ids[2] =
{
    "::FepCmd::CCallAllFep",
    "::Ice::Object"
};

}

bool
FepCmd::CCallAllFep::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__FepCmd__CCallAllFep_ids, __FepCmd__CCallAllFep_ids + 2, _s);
}

::std::vector< ::std::string>
FepCmd::CCallAllFep::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__FepCmd__CCallAllFep_ids[0], &__FepCmd__CCallAllFep_ids[2]);
}

const ::std::string&
FepCmd::CCallAllFep::ice_id(const ::Ice::Current&) const
{
    return __FepCmd__CCallAllFep_ids[0];
}

const ::std::string&
FepCmd::CCallAllFep::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::FepCmd::CCallAllFep";
    return typeId;
#else
    return __FepCmd__CCallAllFep_ids[0];
#endif
}

::Ice::DispatchStatus
FepCmd::CCallAllFep::___CallAllExecute(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::FepCmd::CallAllInfo __p_caInfo;
    __is->read(__p_caInfo);
    __inS.endReadParams();
    CallAllExecute(__p_caInfo, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __FepCmd__CCallAllFep_all[] =
{
    "CallAllExecute",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
FepCmd::CCallAllFep::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__FepCmd__CCallAllFep_all, __FepCmd__CCallAllFep_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __FepCmd__CCallAllFep_all)
    {
        case 0:
        {
            return ___CallAllExecute(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
FepCmd::CCallAllFep::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
FepCmd::CCallAllFep::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
FepCmd::__patch(CCallAllFepPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::FepCmd::CCallAllFepPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::FepCmd::CCallAllFep::ice_staticId(), v);
    }
}
