// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `fepdata.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <fepdata.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __FepData__FepDataManager__processData_name = "processData";

const ::std::string __FepData__FepDataManager__processFault_name = "processFault";

const ::std::string __FepData__FepDataManager__processEvent_name = "processEvent";

const ::std::string __FepData__FepDataManager__processWave_name = "processWave";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::FepData::upCast(::IceProxy::FepData::FepDataManager* p) { return p; }

void
::IceProxy::FepData::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::FepData::FepDataManager>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::FepData::FepDataManager;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::FepData::FepDataManager::processData(const ::FepData::DataPacket& __p_aDataPacket, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __FepData__FepDataManager__processData_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aDataPacket);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::FepData::FepDataManager::begin_processData(const ::FepData::DataPacket& __p_aDataPacket, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FepData__FepDataManager__processData_name, __del, __cookie);
    try
    {
        __result->prepare(__FepData__FepDataManager__processData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aDataPacket);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::FepData::FepDataManager::end_processData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FepData__FepDataManager__processData_name);
}

void
IceProxy::FepData::FepDataManager::processFault(const ::FepData::FaultPacket& __p_aFaultPacket, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __FepData__FepDataManager__processFault_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aFaultPacket);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::FepData::FepDataManager::begin_processFault(const ::FepData::FaultPacket& __p_aFaultPacket, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FepData__FepDataManager__processFault_name, __del, __cookie);
    try
    {
        __result->prepare(__FepData__FepDataManager__processFault_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aFaultPacket);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::FepData::FepDataManager::end_processFault(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FepData__FepDataManager__processFault_name);
}

void
IceProxy::FepData::FepDataManager::processEvent(const ::FepData::EventPacket& __p_aEventPacket, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __FepData__FepDataManager__processEvent_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aEventPacket);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::FepData::FepDataManager::begin_processEvent(const ::FepData::EventPacket& __p_aEventPacket, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FepData__FepDataManager__processEvent_name, __del, __cookie);
    try
    {
        __result->prepare(__FepData__FepDataManager__processEvent_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aEventPacket);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::FepData::FepDataManager::end_processEvent(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FepData__FepDataManager__processEvent_name);
}

void
IceProxy::FepData::FepDataManager::processWave(const ::FepData::WavePacket& __p_aWavePacket, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __FepData__FepDataManager__processWave_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aWavePacket);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::FepData::FepDataManager::begin_processWave(const ::FepData::WavePacket& __p_aWavePacket, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FepData__FepDataManager__processWave_name, __del, __cookie);
    try
    {
        __result->prepare(__FepData__FepDataManager__processWave_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_aWavePacket);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::FepData::FepDataManager::end_processWave(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FepData__FepDataManager__processWave_name);
}

const ::std::string&
IceProxy::FepData::FepDataManager::ice_staticId()
{
    return ::FepData::FepDataManager::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::FepData::FepDataManager::__newInstance() const
{
    return new FepDataManager;
}

::Ice::Object* FepData::upCast(::FepData::FepDataManager* p) { return p; }

namespace
{
const ::std::string __FepData__FepDataManager_ids[2] =
{
    "::FepData::FepDataManager",
    "::Ice::Object"
};

}

bool
FepData::FepDataManager::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__FepData__FepDataManager_ids, __FepData__FepDataManager_ids + 2, _s);
}

::std::vector< ::std::string>
FepData::FepDataManager::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__FepData__FepDataManager_ids[0], &__FepData__FepDataManager_ids[2]);
}

const ::std::string&
FepData::FepDataManager::ice_id(const ::Ice::Current&) const
{
    return __FepData__FepDataManager_ids[0];
}

const ::std::string&
FepData::FepDataManager::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::FepData::FepDataManager";
    return typeId;
#else
    return __FepData__FepDataManager_ids[0];
#endif
}

::Ice::DispatchStatus
FepData::FepDataManager::___processData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::FepData::DataPacket __p_aDataPacket;
    __is->read(__p_aDataPacket);
    __inS.endReadParams();
    processData(__p_aDataPacket, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
FepData::FepDataManager::___processFault(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::FepData::FaultPacket __p_aFaultPacket;
    __is->read(__p_aFaultPacket);
    __inS.endReadParams();
    processFault(__p_aFaultPacket, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
FepData::FepDataManager::___processEvent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::FepData::EventPacket __p_aEventPacket;
    __is->read(__p_aEventPacket);
    __inS.endReadParams();
    processEvent(__p_aEventPacket, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
FepData::FepDataManager::___processWave(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::FepData::WavePacket __p_aWavePacket;
    __is->read(__p_aWavePacket);
    __inS.endReadParams();
    processWave(__p_aWavePacket, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __FepData__FepDataManager_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "processData",
    "processEvent",
    "processFault",
    "processWave"
};

}

::Ice::DispatchStatus
FepData::FepDataManager::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__FepData__FepDataManager_all, __FepData__FepDataManager_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __FepData__FepDataManager_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___processData(in, current);
        }
        case 5:
        {
            return ___processEvent(in, current);
        }
        case 6:
        {
            return ___processFault(in, current);
        }
        case 7:
        {
            return ___processWave(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
FepData::FepDataManager::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
FepData::FepDataManager::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
FepData::__patch(FepDataManagerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::FepData::FepDataManagerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::FepData::FepDataManager::ice_staticId(), v);
    }
}
