// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `amssrv.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.kh.ams.Amssrv;

/**
 * AMS Manager对外接口
 *
 **/
public interface CAmsApp extends Ice.Object,
                                 _CAmsAppOperations, _CAmsAppOperationsNC
{
    public static final String ice_staticId = "::Amssrv::CAmsApp";

    public static final long serialVersionUID = 335441864L;
}
