

#ifndef DB_TABLE_NAME_H
#define DB_TABLE_NAME_H

#define GeographicalRegion_ID 		"GeographicalRegion"
#define SubGeographicalRegion_ID 	"SubGeographicalRegion"
#define Area_ID					 	"Area"
#define Substation_ID 				"Substation"
#define BaseVoltage_ID 				"BaseVoltage"
#define VoltageLevel_ID 			"VoltageLevel"
#define Bay_ID 						"Bay"
#define Line_ID						"Line"
#define PowerTransformer_ID			"PowerTransformer"
#define TransformerWinding_ID		"TransformerWinding"
#define ConnectivityNode_ID			"ConnectivityNode"
#define BusbarSection_ID			"BusbarSection"
#define Terminal_ID					"Terminal"
#define Breaker_ID					"Breaker"
#define Disconnector_ID				"Disconnector"
#define ACLineSegment_ID			"ACLineSegment"
#define Analog_ID					"Analog"
#define Discrete_ID					"Discrete"
#define Accumulator_ID				"Accumulator"
#define Command_ID					"Command"
#define FormulaDefinition_ID		"FormulaDefinition"
#define VariableDefinition_ID		"VariableDefinition"
#define ControlLockingFormula_ID	"ControlLocingFormula"
#define Step_ID						"Step"
#define RemoteUnit_ID 				"RemoteUnit"
#define AnalogUnitPoint_ID 			"AnalogUnitPoint"
#define DiscreteUnitPoint_ID 		"DiscreteUnitPoint"
#define ControlUnitPoint_ID 		"ControlUnitPoint"
#define AccumulatorUnitPoint_ID 		"AccumulatorUnitPoint"
#define DevManufacturer_ID 			"DevManufacturer"
#define DevDeviceType_ID 			"DevDeviceType"
#define DevSettingLine_ID 			"DevSettingLine"
#define DevSettingType_ID 			"DevSettingType"
#define ConfigFaultDesc_ID			"ConfigFaultDesc"
#define ConfigYxDesc_ID				"ConfigYxDesc"
#define SystemUser_ID				"SystemUser"
#define SecurityGroups_ID			"SecurityGroups"
#define SecurityGroupsUsers_ID		"SecurityGroupsUsers"
#define SecurityGroupsStations_ID	"SecurityGroupsStations"
#define AnalogCurveData_ID			"AnalogCurveData"
#define ProtectValue_ID				"ProtectValue"
#define FepPartition_ID				"FepPartition"
#define FepSection_ID				"FepSection"
#define FepProtocol_ID				"FepProtocol"
#define FepChannel_ID				"FepChannel"
#define FepProtocolUnit_ID			"FepProtocolUnit"
#define SystemRole_ID				"SystemRole"
#define SystemPhone_ID				"SystemPhone"
#define SystemMsgCfg_ID				"SystemMsgCfg"
#define GraphFile_ID				"GraphFile"
#define WavWaveConfig_ID			"WavWaveConfig"
#define WavTrendCurve_ID			"WavTrendCurve"
#define AccumulatorTimeSegment_ID			"AccumulatorTimeSegment"
#define FATopo_ID					"FATopo"
#endif
