// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ykdata.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.icestorm.Yk;

public interface _YkAppManagerOperations
{
    /**
     * @param: cmd - 遥控命令。
     * @param: flag - true表示操作正常，false表示操作异常。
     * @param: tip - flag=true，tip=""；flag=false，tip提示出错原因。
     * @param __current The Current object for the invocation.
     **/
    void selectEcho(YkCommand cmd, boolean flag, String tip, Ice.Current __current);

    void selectReturn(YkCommand cmd, boolean flag, String tip, Ice.Current __current);

    void executeEcho(YkCommand cmd, boolean flag, String tip, Ice.Current __current);

    void executeReturn(YkCommand cmd, boolean flag, String tip, Ice.Current __current);

    void cancelEcho(YkCommand cmd, boolean flag, String tip, Ice.Current __current);

    void cancelReturn(YkCommand cmd, boolean flag, String tip, Ice.Current __current);
}
