// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ykdata.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.icestorm.Yk;

public interface YkFepManager extends Ice.Object,
                                      _YkFepManagerOperations, _YkFepManagerOperationsNC
{
    public static final String ice_staticId = "::Yk::YkFepManager";

    public static final long serialVersionUID = 130688541L;
}
