// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `warningmsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.warningmsg.WarningMsg;

public interface _SendWarningMsgOperationsNC
{
    void sendWarningMsgBinary(String title, byte[] datas);

    /**
     * 发送录波文件
     * @parameter unitNo: 单元号
     * @parameter title: 文件标题
     * @parameter datas: 文件内容
     *
     **/
    void sendRfwFileBinary(String unitNo, String title, byte[] datas);

    /**
     * 发送历史曲线文件
     * @parameter date: 日期
     * @parameter title: 文件标题
     * @parameter datas: 文件内容
     *
     **/
    void sendCurveFileBinary(String date, String title, byte[] datas);
}
