// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `warningmsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.warningmsg.WarningMsg;

public interface SendWarningMsg extends Ice.Object,
                                        _SendWarningMsgOperations, _SendWarningMsgOperationsNC
{
    public static final String ice_staticId = "::WarningMsg::SendWarningMsg";

    public static final long serialVersionUID = -1248590367L;
}
