// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `warningmsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.warningmsg.WarningMsg;

public final class WarningMsgFileHolder extends Ice.ObjectHolderBase<WarningMsgFile>
{
    public
    WarningMsgFileHolder()
    {
    }

    public
    WarningMsgFileHolder(WarningMsgFile value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof WarningMsgFile)
        {
            value = (WarningMsgFile)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _WarningMsgFileDisp.ice_staticId();
    }
}
