// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `warningmsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gridnt.warningmsg.WarningMsg;

public interface WarningMsgFilePrx extends Ice.ObjectPrx
{
    /**
     * 读取报警文件内容
     * @parameter pos:上次读取文件位置
     * @parameter length:读取行数
     * @parameter strFilename:文件名称
     * @return LogContent
     **/
    public WarningMsgContent getContent(long pos, int length, String strFilename);

    /**
     * 读取报警文件内容
     * @parameter pos:上次读取文件位置
     * @parameter length:读取行数
     * @parameter strFilename:文件名称
     * @param __ctx The Context map to send with the invocation.
     * @return LogContent
     **/
    public WarningMsgContent getContent(long pos, int length, String strFilename, java.util.Map<String, String> __ctx);

    /**
     * 读取报警文件内容
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename);

    /**
     * 读取报警文件内容
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename, java.util.Map<String, String> __ctx);

    /**
     * 读取报警文件内容
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename, Ice.Callback __cb);

    /**
     * 读取报警文件内容
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 读取报警文件内容
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename, Callback_WarningMsgFile_getContent __cb);

    /**
     * 读取报警文件内容
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, int length, String strFilename, java.util.Map<String, String> __ctx, Callback_WarningMsgFile_getContent __cb);

    /**
     * 读取报警文件内容
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, 
                                            int length, 
                                            String strFilename, 
                                            IceInternal.Functional_GenericCallback1<WarningMsgContent> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 读取报警文件内容
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, 
                                            int length, 
                                            String strFilename, 
                                            IceInternal.Functional_GenericCallback1<WarningMsgContent> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 读取报警文件内容
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, 
                                            int length, 
                                            String strFilename, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<WarningMsgContent> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 读取报警文件内容
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getContent(long pos, 
                                            int length, 
                                            String strFilename, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<WarningMsgContent> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 读取报警文件内容
     * @param __result The asynchronous result object.
     * @return LogContent
     **/
    public WarningMsgContent end_getContent(Ice.AsyncResult __result);
}
