// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `wavefepapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.kh.scada.wavefepapp;

public interface RfwAppManager extends Ice.Object,
                                       _RfwAppManagerOperations, _RfwAppManagerOperationsNC
{
    public static final String ice_staticId = "::wavefepapp::RfwAppManager";

    public static final long serialVersionUID = -1991896965L;
}
